config/routes.rb
Rails.application.routes.draw do
  resources :engineers

  resources :proyects

  resources :proyects do
  resources :engineers
  end

  root 'proyects#index'

end

app/models/engineer.rb
class Engineer < ActiveRecord::Base
  belongs_to :proyect
end

app/models/proyect.rb
class Proyect < ActiveRecord::Base
    has_many :engineers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: [:show, :edit, :update, :destroy,:index, :new, :create]

  # GET /engineers
  # GET /engineers.json
  def index
    @engineers = @proyect.engineers.all # lista solo los ingenieros de ese proyecto no todos
  end

  # GET /engineers/1
  # GET /engineers/1.json
  def show
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
  end

  # POST /engineers
  # POST /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)
    @engineer.proyect_id = @proyect.id
    respond_to do |format|
      if @engineer.save
        format.html { redirect_to  proyect_engineers_path(@proyect), notice: 'Engineer was successfully created.' }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1
  # PATCH/PUT /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to proyect_engineers_path(@proyect) , notice: 'Engineer was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1
  # DELETE /engineers/1.json
  def destroy
    @engineer.destroy
    respond_to do |format|
      format.html { redirect_to proyect_engineers_url(@proyect), notice: 'Engineer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_engineer
    @proyect = Proyect.find(params[:proyect_id]) # recupera el proyecto
    @engineer = Engineer.find(params[:id]) if params[:id] # recupera el id solo si lo envian
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_params
      params.require(:engineer).permit(:fullname, :dependency, :studies, :proyect_id)
    end
end

app/controllers/proyects_controller.rb
class ProyectsController < ApplicationController
  before_action :set_proyect, only: [:show, :edit, :update, :destroy]

  # GET /proyects
  # GET /proyects.json
  def index
    @proyects = Proyect.all
  end

  # GET /proyects/1
  # GET /proyects/1.json
  def show
  end

  # GET /proyects/new
  def new
    @proyect = Proyect.new
  end

  # GET /proyects/1/edit
  def edit
  end

  # POST /proyects
  # POST /proyects.json
  def create
    @proyect = Proyect.new(proyect_params)

    respond_to do |format|
      if @proyect.save
        format.html { redirect_to @proyect, notice: 'Proyect was successfully created.' }
        format.json { render :show, status: :created, location: @proyect }
      else
        format.html { render :new }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /proyects/1
  # PATCH/PUT /proyects/1.json
  def update
    respond_to do |format|
      if @proyect.update(proyect_params)
        format.html { redirect_to @proyect, notice: 'Proyect was successfully updated.' }
        format.json { render :show, status: :ok, location: @proyect }
      else
        format.html { render :edit }
        format.json { render json: @proyect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proyects/1
  # DELETE /proyects/1.json
  def destroy
    @proyect.destroy
    respond_to do |format|
      format.html { redirect_to proyects_url, notice: 'Proyect was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_proyect
      @proyect = Proyect.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def proyect_params
      params.require(:proyect).permit(:name, :description, :begindate, :enddate)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/helpers/proyects_helper.rb
module ProyectsHelper
end

app/views/engineers/_form.html.erb
<%= simple_form_for [@proyect,@engineer], :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :fullname %>
  <%= f.input :dependency %>
  <%= f.input :studies %>
  <%= f.input :proyect_id %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            	proyect_engineers_path(@proyect), :class => 'btn' %>

<% end %>

app/views/engineers/edit.html.erb
<%- model_class = Engineer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/engineers/index.html.erb
<%- model_class = Engineer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:fullname) %></th>
      <th><%= model_class.human_attribute_name(:dependency) %></th>
      <th><%= model_class.human_attribute_name(:studies) %></th>
      <th><%= model_class.human_attribute_name(:proyect_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @engineers.each do |engineer| %>
      <tr>
        <td><%= link_to engineer.id, engineer_path(engineer) %></td>
        <td><%= engineer.fullname %></td>
        <td><%= engineer.dependency %></td>
        <td><%= engineer.studies %></td>
        <td><%= engineer.proyect_id %></td>
        <td><%=l engineer.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_proyect_engineer_path(@proyect,engineer), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      proyect_engineer_path(@proyect,engineer),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

         <%= link_to t('.new', :default => t("helpers.links.new")),
          new_proyect_engineer_path(@proyect),
          :class => 'btn btn-primary' %>

app/views/engineers/new.html.erb
<%- model_class = Engineer -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/engineers/show.html.erb
<%- model_class = Engineer -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:fullname) %>:</strong></dt>
  <dd><%= @engineer.fullname %></dd>
  <dt><strong><%= model_class.human_attribute_name(:dependency) %>:</strong></dt>
  <dd><%= @engineer.dependency %></dd>
  <dt><strong><%= model_class.human_attribute_name(:studies) %>:</strong></dt>
  <dd><%= @engineer.studies %></dd>
  <dt><strong><%= model_class.human_attribute_name(:proyect_id) %>:</strong></dt>
  <dd><%= @engineer.proyect_id %></dd>
</dl>


<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              engineers_path, :class => 'btn'  %>

  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_engineer_path(@engineer), :class => 'btn' %>
  
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              engineer_path(@engineer),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ror4x</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/proyects/_form.html.erb
<%= simple_form_for @proyect, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :begindate %>
  <%= f.input :enddate %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                proyects_path, :class => 'btn' %>
  </div>
<% end %>

app/views/proyects/edit.html.erb
<%- model_class = Proyect -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/proyects/index.html.erb
<%- model_class = Proyect -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:begindate) %></th>
      <th><%= model_class.human_attribute_name(:enddate) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @proyects.each do |proyect| %>
      <tr>

        <td><%= link_to 'Equipo', proyect_engineers_path(proyect) %></td>
        <td><%= link_to proyect.id, proyect_path(proyect) %></td>
        <td><%= proyect.name %></td>
        <td><%= proyect.description %></td>
        <td><%= proyect.begindate %></td>
        <td><%= proyect.enddate %></td>
        <td><%=l proyect.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_proyect_path(proyect), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      proyect_path(proyect),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_proyect_path,
            :class => 'btn btn-primary' %>

app/views/proyects/new.html.erb
<%- model_class = Proyect -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/proyects/show.html.erb
<%- model_class = Proyect -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @proyect.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @proyect.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:begindate) %>:</strong></dt>
  <dd><%= @proyect.begindate %></dd>
  <dt><strong><%= model_class.human_attribute_name(:enddate) %>:</strong></dt>
  <dd><%= @proyect.enddate %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              proyects_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_proyect_path(@proyect), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              proyect_path(@proyect),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>